Region: us-east-1
Profile: local

# AWS Services
IAM:
  DeploymentRole: arn:aws:iam::000000000000:role/monitoring-DeploymentRole

S3:
  DeploymentBucket:
    Name: monitoring-local-deployment

Lambda:
  Environment:
    LOG_LEVEL: DEBUG
  LogRetentionInDays: 7

DynamoDB:
  BillingMode: PAY_PER_REQUEST

MonitoringConfigs:
  Health:
    State: enabled
  GuardDuty:
    State: enabled
  CloudwatchLogs:
    State: enabled
    Schedule: rate(15 minutes)
    Query: |
      fields @message, @log, @logStream
      | filter @message like /(?i)(error|fail|exception)/
      | sort @timestamp desc
      | limit 200

  Webhooks:
    Monitoring: "https://hooks.slack.com/services/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"
    Deployment: "https://hooks.slack.com/services/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"
    Report: "https://hooks.slack.com/services/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"
